"""add achievement_type to pre_entry tables

Revision ID: 59994aa2a6eb
Revises: 80eefd4e130e
Create Date: 2025-07-12 16:28:58.648024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59994aa2a6eb'
down_revision: Union[str, None] = '80eefd4e130e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 只添加achievement_type字段到pre_entry表，不删除其他表
    with op.batch_alter_table('bs_pre_entry_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_type', sa.Integer(), nullable=True, server_default='0'))
        batch_op.create_index(batch_op.f('ix_bs_pre_entry_book_achievement_type'), ['achievement_type'], unique=False)

    with op.batch_alter_table('bs_pre_entry_competition_award', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_type', sa.Integer(), nullable=True, server_default='0'))
        batch_op.create_index(batch_op.f('ix_bs_pre_entry_competition_award_achievement_type'), ['achievement_type'], unique=False)

    with op.batch_alter_table('bs_pre_entry_conference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_type', sa.Integer(), nullable=True, server_default='0'))
        batch_op.create_index(batch_op.f('ix_bs_pre_entry_conference_achievement_type'), ['achievement_type'], unique=False)

    with op.batch_alter_table('bs_pre_entry_industry_standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_type', sa.Integer(), nullable=True, server_default='0'))
        batch_op.create_index(batch_op.f('ix_bs_pre_entry_industry_standard_achievement_type'), ['achievement_type'], unique=False)

    with op.batch_alter_table('bs_pre_entry_new_variety', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_type', sa.Integer(), nullable=True, server_default='0'))
        batch_op.create_index(batch_op.f('ix_bs_pre_entry_new_variety_achievement_type'), ['achievement_type'], unique=False)

    with op.batch_alter_table('bs_pre_entry_paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_type', sa.Integer(), nullable=True, server_default='0'))
        batch_op.create_index(batch_op.f('ix_bs_pre_entry_paper_achievement_type'), ['achievement_type'], unique=False)

    with op.batch_alter_table('bs_pre_entry_patent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_type', sa.Integer(), nullable=True, server_default='0'))
        batch_op.create_index(batch_op.f('ix_bs_pre_entry_patent_achievement_type'), ['achievement_type'], unique=False)

    with op.batch_alter_table('bs_pre_entry_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_type', sa.Integer(), nullable=True, server_default='0'))
        batch_op.create_index(batch_op.f('ix_bs_pre_entry_project_achievement_type'), ['achievement_type'], unique=False)

    with op.batch_alter_table('bs_pre_entry_subject_research', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_type', sa.Integer(), nullable=True, server_default='0'))
        batch_op.create_index(batch_op.f('ix_bs_pre_entry_subject_research_achievement_type'), ['achievement_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('bs_pre_entry_subject_research', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bs_pre_entry_subject_research_achievement_type'))
        batch_op.drop_column('achievement_type')

    with op.batch_alter_table('bs_pre_entry_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bs_pre_entry_project_achievement_type'))
        batch_op.drop_column('achievement_type')

    with op.batch_alter_table('bs_pre_entry_patent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bs_pre_entry_patent_achievement_type'))
        batch_op.drop_column('achievement_type')

    with op.batch_alter_table('bs_pre_entry_paper', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bs_pre_entry_paper_achievement_type'))
        batch_op.drop_column('achievement_type')

    with op.batch_alter_table('bs_pre_entry_new_variety', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bs_pre_entry_new_variety_achievement_type'))
        batch_op.drop_column('achievement_type')

    with op.batch_alter_table('bs_pre_entry_industry_standard', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bs_pre_entry_industry_standard_achievement_type'))
        batch_op.drop_column('achievement_type')

    with op.batch_alter_table('bs_pre_entry_conference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bs_pre_entry_conference_achievement_type'))
        batch_op.drop_column('achievement_type')

    with op.batch_alter_table('bs_pre_entry_competition_award', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bs_pre_entry_competition_award_achievement_type'))
        batch_op.drop_column('achievement_type')

    with op.batch_alter_table('bs_pre_entry_book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bs_pre_entry_book_achievement_type'))
        batch_op.drop_column('achievement_type')

    # ### end Alembic commands ###
